INSERT INTO `course`
VALUES (1, 'Java Programming Masterclass',
        'Learn Java In This Course And Become a Computer Programmer. Obtain valuable Core Java Skills And Java Certification',
        57, 1, 1, 0, 28, 1, 0, 2, 'static/images/java.jpg'),
       (2, 'Java Programming for Complete Beginners',
        'Java Programming Course for Beginners to Java Object Oriented Programming. BONUS: Build REST API with Spring Boot.',
        60, 1, 1, 12, 33, 0, 0, NULL, 'static/images/java.jpg'),
       (3, 'Learn Python Programming Masterclass',
        'This Python For Beginners Course Teaches You The Python Language Fast. Includes Python Online Training With Python 3',
        23, 4, 1, 23, 65, 0, 0, NULL, 'static/images/python.png'),
       (4, 'Изучение C++ с нуля', 'Изучение языка программирования С++ с легкостью и простым языком', 23, 3, 1, 34,
        76, 0, 0, NULL, 'static/images/c++.png'),
       (5, 'Advanced C Programming Course',
        'Become a True Master of the C Programming Language - Confidently Apply for Real Time or Embedded C Jobs or contracts!',
        23, 2, 2, 21, 44, 0, 0, NULL, 'static/images/c.png'),
       (6, 'Beginning C++ Programming - From Beginner to Beyond',
        'Obtain Modern C++ Object-Oriented Programming (OOP) and STL skills. C++14 and C++17 covered. C++20 info see below.',
        12, 3, 2, 44, 64, 1, 0, NULL, 'static/images/c++.png'),
       (7, 'Learn Python: The Complete Python Programming Course',
        'Learn A-Z everything about Python, from the basics, to advanced topics like Python GUI, Python Data Analysis, and more!',
        0, 4, 2, 0, 0, 0, 1, NULL, 'static/images/python.png'),
       (8, 'Learning Python for Data Analysis and Visualization',
        'Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!',
        0, 4, 2, 0, 0, 1, 0, NULL, 'static/images/python.png'),
       (9, 'The Complete Java Certification Course',
        'Become a confident industry ready core Java developer and get certified as a Java professional!', 0, 1, 1, 0,
        0, 0, 0, NULL, 'static/images/java.jpg'),
       (10, 'Become a confident industry ready core Java developer!',
        'Learn Java In This Course And Become a Computer Programmer. Obtain valuable Core Java Skills And Java Certification',
        0, 1, 1, 0, 0, 0, 0, NULL, 'static/images/java.jpg'),
       (11, 'Learn Spring Data JPA with Hibernate: The Masterclass',
        'Learn Spring Data JPA features and learn building domain model relationships for E-Commerce project using Hibernate ORM.',
        0, 1, 2, 0, 0, 0, 1, NULL, 'static/images/java.jpg');
